n=input("Digite o nome do cliente: ")
d=input("Digite o dia de vencimento: ")
m=input("Digite o mês de vencimento: ")
v=input("Digite o valor da fatura: ")
print("Olá,",n)
print("A sua fatura com vencimento em",d,"de",m,"no valor de R$",v,"está fechada.")
